TxWeb/FXAdminTransferConnex/Controllers/RegionController.cs
using System.Web.Mvc;
using FXAdminTransferConnex.Business.Region;
using FXAdminTransferConnex.Common;
using FXAdminTransferConnex.Entities;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using FXAdminTransferConnex.Entities.LocalizationResource;
using System;
using System.Linq;
using System.Collections.Generic;

namespace FXAdminTransferConnexApp.Controllers
{
    public class RegionController : BaseAdminController
    {
        

        /// <summary>
        /// The usersService service
        /// </summary>
        private readonly IRegionService _RegionService;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserController"/> class.
        /// </summary>
        public RegionController()
        {
            _RegionService = EngineContext.Resolve<IRegionService>();
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetRegion([DataSourceRequest]DataSourceRequest request, string search="")
        {
            List<RegionMasterModel> RegionList = _RegionService.GetRegion(0,search);
            return Json(RegionList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);

        }


        public ActionResult GetRegionListForDisplay()
        {
            List<RegionMasterModel> RegionList = _RegionService.GetRegion(0, "");
            return new JsonResult
            {
                Data = RegionList,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult DeleteRegion([DataSourceRequest]DataSourceRequest request, RegionMasterModel obj)
        {
            bool result = _RegionService.DeleteRegion(obj.RegionID);
            return Json(result
                ? new { Message = FXAdminTransferConnexResource.DeleteSuccess, IsError = Enums.NotifyType.Success }
                : new { Message = FXAdminTransferConnexResource.Failed, IsError = Enums.NotifyType.Error }
                , JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public ActionResult ManageRegion(int id = -1)
        {
            RegionMasterModel model = new RegionMasterModel();
            List<RegionMasterModel> RegionModel = _RegionService.GetRegion(id,"");
            if (RegionModel != null)
            {
                model = RegionModel.FirstOrDefault();
            }            
            return View(model);
        }

        [HttpPost]
        public ActionResult ManageRegion(RegionMasterModel model)
        {
            if (model.RegionID > 0)
            {
                SuccessNotification("Region Updated Successfully");
                model.UpdatedBy = ProjectSession.LoginUserDetails.UserId;
                _RegionService.UpdateRegion(model);
            }
            else
            {
                SuccessNotification("User Saved Successfully");
                model.CreatedBy = ProjectSession.LoginUserDetails.UserId;
                _RegionService.AddRegion(model);
            }
            
            return RedirectToAction("Index");
        }        
    }
}

TxWeb/FXAdminTransferConnex/Views/Region/Index.cshtml
@using FXAdminTransferConnex.Entities;
@using FXAdminTransferConnexApp
@using FXAdminTransferConnex.Common

@using Kendo.Mvc.UI

<div class="content">
    <legend>Region</legend>
    <div class="panel panel-default">
        <div class="panel-body pb-0">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <input id="txtsearch" type="text" placeholder="Search" class="k-textbox" />
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <button id="search" type="button" class="k-button btn-orange">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @* GRID HERE *@

    <fieldset>
        <legend></legend>
        <div class="panel panel-default">
            <div class="panel-body">

                @(Html.Kendo().Grid<RegionMasterModel>()
                  .Name("gridUser")
                  .Columns(columns =>
                  {
                      columns.Bound(m => m.RegionName).Width(150);
                      columns.Command(command =>
                      {

                          command.Custom("Edit").Text("<span class='k-icon k-edit'></span>").Click("onInsert").HtmlAttributes(new { @style = "margin:2px" });

                          command.Destroy().Text(" ").HtmlAttributes(new { @style = "margin:2px" });


                          //command.Custom("Edit").Text("<a  href='" +
                          // Url.Action("ManageUser", "User") + "?id=#= UserId #'" + "> <span class='k-icon k-edit'></span></a>");
                          //command.Edit().CancelText("Cancel").Text(" ").UpdateText("Save");

                      })
                          .HeaderHtmlAttributes(Common.CenterColumnStyle)
                          .HtmlAttributes(Common.CenterColumnStyle)
                          .Title("Action")
                          .Width(150);
                  })
                  .ToolBar(toolbar =>
                  {
                    
                          toolbar.Custom().Text("Add Region").Url(Url.Action("ManageRegion", "Region")).HtmlAttributes(new { @class = "k-button btn-orange" });
                    

                  })
                  .Editable(e => e.Mode(GridEditMode.PopUp))
                  .Pageable(x =>
                  {
                      x.Refresh(false);
                      x.PageSizes(new int[] { 10, 20, 50, 100 });
                  })
                  .Selectable(selectable => selectable
                  .Mode(GridSelectionMode.Single))
                  .Navigatable()
                  //.Scrollable(scrollable => scrollable.Height("auto"))
                  .Sortable(sortable => sortable.AllowUnsort(false))
                  .NoRecords()
                  //.Events(grid => grid.Edit("edit"))
                  .DataSource(dataSource => dataSource
                      .Ajax()
                      .ServerOperation(false)                      
                      .Model(model =>
                      {
                          model.Id(d => d.RegionID);
                      })
                   //.Create(update => update.Action("AddUserDetails", "User"))
                   //.Update(update => update.Action("AddUserDetails", "User"))
                   .Destroy(delete => delete.Action("DeleteRegion", "Region"))
                   .Read(read => read.Action("GetRegion", "Region"))
                    .Events(events => events.RequestEnd("onRequestEnd"))
                  ))
            </div>
        </div>
    </fieldset>
</div>
<script>
    $(document).ready(function () {
        kendoGridScroll();
    });

    $('.k-pager-refresh').click(function () {
        $('#txtsearch').val('');
    });

    $("#search").click(function () {
        //if ($('#txtsearch').val() !== "") {
        $('#gridUser').data('kendoGrid').dataSource.read({ Search: $('#txtsearch').val().trim() });
        $('#gridUser').data().kendoGrid.dataSource.page(1);
        //}
    });

    $('#txtsearch').keypress(function (e) {
        var key = e.which;
        if (key == 13)  // the enter key code
        {
            if ($('#txtsearch').val() !== "") {
                $('#gridUser').data('kendoGrid').dataSource.read({ Search: $('#txtsearch').val().trim() });
                $('#gridUser').data().kendoGrid.dataSource.page(1);
            }
        }
    });

    //Shows the notifications
    function onRequestEnd(para) {
        if (para.type == 'update' || para.type == 'create' || para.type == 'destroy') {
            $('#gridUser').data('kendoGrid').dataSource.read();
        }
        DisplayResponseMessage(para);
    }

    function onInsert(e) {
        var userId = 0;

        if (e != 0) {
            e.preventDefault();
            var tr = $(e.target).closest("tr");
            var data = this.dataItem(tr);

            if (data != null) {
                userId = data.RegionId;
            }
        }
        var urllink = '@Url.Action("ManageRegion", "Region")';
        window.location.href = urllink + "?id=" + userId;
    }
</script>

TxWeb/FXAdminTransferConnex/Views/Region/ManageRegion.cshtml
@using Kendo.Mvc.UI;
@using FXAdminTransferConnex.Entities;
@using FXAdminTransferConnexApp
@using FXAdminTransferConnex.Common

@model FXAdminTransferConnex.Entities.RegionMasterModel

@{
    ViewBag.Title = "ManageRegion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ManageRegion", "Region", FormMethod.Post))
{

    @Html.HiddenFor(m => m.RegionID)
    <div class="panel panel-default">
        <div class="panel-body">
            <h2 class="category-title">
                Region Detail
            </h2>
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Region Name:</label>
                            @Html.TextBoxFor(m => m.RegionName, new { @placeholder = "Region name", @class = "form-control", @tabindex = "1" })
                            @Html.ValidationMessageFor(m => m.RegionName)                           
                        </div>
                    </div>
                </div>


                <div class="col-md-12">
                    <a href="@Url.Action("Index","Region")" class="btn btn-orange mt-5 mr-10 pull-right" tabindex="16">Cancel</a>
                    <button class="btn btn-orange mt-5 mr-10 pull-right" type="submit" tabindex="15">Save</button>
                </div>

            </div>
        </div>
    </div>

}