TxWeb/FXAdminTransferConnex/Controllers/BulkEmailController.cs
using FXAdminTransferConnex.Business.BulkEmail;
using FXAdminTransferConnex.Business.Client;
using FXAdminTransferConnex.Business.Common;
using FXAdminTransferConnex.Business.Prospect;
using FXAdminTransferConnex.Common;
using FXAdminTransferConnex.Entities;
using FXAdminTransferConnexApp.LocalizationResource;
using Kendo.Mvc;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FXAdminTransferConnexApp.Controllers
{
    public class BulkEmailController : BaseAdminController
    {
        #region Initializations

        /// <summary>
        /// The usersService service
        /// </summary>
        private readonly IBulkEmailService _bulkemailService;
        private readonly IProspectService _prospectService;

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientController"/> class.
        /// </summary>
        public BulkEmailController()
        {
            _bulkemailService = EngineContext.Resolve<IBulkEmailService>();
            _prospectService = EngineContext.Resolve<IProspectService>();
        }
        #endregion

        // GET: BulkEmail
        public ActionResult Index()
        {
            ViewBag.IsAwaitingAction = "2";
            ViewBag.IsMarketOrder = "2";

            if (!string.IsNullOrEmpty(Request.QueryString["IsAwaitingAction"]))
                ViewBag.IsAwaitingAction = Request.QueryString["IsAwaitingAction"].ToString();

            if (!string.IsNullOrEmpty(Request.QueryString["IsMarketOrder"]))
                ViewBag.IsMarketOrder = Request.QueryString["IsMarketOrder"].ToString();

            return View();
        }

        /// <summary>
        /// By Mayank
        /// 12 March 2018
        /// Get client list
        /// </summary>
        /// <param name="request"></param>
        /// <param name="FullName"></param>
        /// <param name="CompanyName"></param>
        /// <param name="AccountNo"></param>
        /// <param name="EmailAddress"></param>
        /// <param name="AwaitingAction"></param>
        /// <param name="MarketOrder"></param>
        /// <returns></returns>
        public ActionResult GetClientList([DataSourceRequest]DataSourceRequest request, string FullName, string EmailAddress, string CompanyName, string AccountNo, string AwaitingAction = "2", string MarketOrder = "2", string SearchType = null)
        {
            int pageNo = request.Page;
            int pageSize = request.PageSize;
            string sortColumn = string.Empty;
            string sortDir = string.Empty;

            foreach (SortDescriptor sort in request.Sorts)
            {
                sortColumn = sort.Member;

                if (sort.SortDirection == System.ComponentModel.ListSortDirection.Ascending)
                {
                    sortDir = "ASC";
                }
                else
                {
                    sortDir = "DESC";
                }
            }

            List<ClientMasterModel> clientList = _bulkemailService.GetAllClientlist(pageNo, pageSize, sortColumn, sortDir, FullName, EmailAddress, CompanyName, AccountNo, AwaitingAction, MarketOrder, SearchType);

            if (clientList != null && clientList.Count > 0)
            {
                DataSourceResult obj = new DataSourceResult();
                obj.Data = clientList;
                if (clientList.Count > 0)
                {
                    obj.Total = clientList.FirstOrDefault().TotalCount;
                }

                return Json(obj, JsonRequestBehavior.AllowGet);
            }

            return Json(new List<ClientMasterModel>(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult SendMail(string[] clientEmail, string subject, string body)
        {
            return Json(null);
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult SendMail(string[] emaillist, string subject, string body, string Signature = "TransferConnex")
        {
            string emails = string.Join(",", emaillist);
            emails = emails.Replace('/', ',').Trim();

            List<List<string>> list = ListExtensions.ChunkBy(emaillist.ToList(), 100);

            for (int i = 0; i < list.Count; i++)
            {
                emails = string.Join(",", list[i]);
                bool result = _bulkemailService.SendMail(emails, subject, body);
                if (i == list.Count - 1)
                {
                    return Json(result
                            ? new { Message = FXSystemResource.SendEmailSuccess, IsError = Enums.NotifyType.Success }
                            : new { Message = FXSystemResource.SendEmailFailed, IsError = Enums.NotifyType.Error }
                            , JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { Message = FXSystemResource.Failed, IsError = Enums.NotifyType.Error }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GenerateDrafts(string[] emailTo, string Subject, string emailType)
        {
            List<ServiceFile> serviceFile = new List<ServiceFile>();
            string filePath = "";
            string guid = Guid.NewGuid().ToString();
            string Body = string.Empty;
            string SenderName = ProjectSession.LoginUserDetails.FirstName + " " + ProjectSession.LoginUserDetails.LastName;

            try    /// GENERATING AN EMAIL DRAFT
            {
                if (emailType.ToUpper() == "EML1")
                {
                    string template1Path = System.Web.HttpContext.Current.Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["EMLTemplate1"]);
                    string attachment1Path = System.Web.HttpContext.Current.Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["EMLAttachments1"]);

                    string strbody = CommonService.ReadTextFile(template1Path);
                    strbody = strbody.Replace("{{Sender}}", SenderName);
                    Body = strbody;
                    string[] filePaths = Directory.GetFiles(attachment1Path);

                    if (filePaths != null)
                    {
                        serviceFile = new List<ServiceFile>();
                        foreach (string item in filePaths)
                        {
                            ServiceFile model = new ServiceFile
                            {
                                FileName = Path.GetFileName(item),
                                FileBytes = System.IO.File.ReadAllBytes(item)
                            };

                            serviceFile.Add(model);
                        }
                    }
                }
                else
                {
                    if (emailType.ToUpper() == "EML2")
                    {
                        string template2Path = System.Web.HttpContext.Current.Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["EMLTemplate2"]);
                        string attachment2Path = System.Web.HttpContext.Current.Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["EMLAttachments2"]);

                        string strbody = CommonService.ReadTextFile(template2Path);
                        strbody = strbody.Replace("{{Sender}}", SenderName);
                        Body = strbody;
                        string[] filePaths = Directory.GetFiles(attachment2Path);

                        if (filePaths != null)
                        {
                            serviceFile = new List<ServiceFile>();
                            foreach (string item in filePaths)
                            {
                                ServiceFile model = new ServiceFile
                                {
                                    FileName = Path.GetFileName(item),
                                    FileBytes = System.IO.File.ReadAllBytes(item)
                                };

                                serviceFile.Add(model);
                            }
                        }
                    }
                    else
                    {
                        if (emailType.ToUpper() == "NEWBLANK")
                        {
                            string blankTemplatePath = System.Web.HttpContext.Current.Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["EMLNewBlank"]);
                            string strbody = CommonService.ReadTextFile(blankTemplatePath);
                            strbody = strbody.Replace("{{Sender}}", SenderName);
                            Body = strbody;
                        }
                    }
                }

                /// Default emails in case they are empty
                MailAddress defaultFrom = new MailAddress(ProjectSession.LoginUserDetails.Email);
                MailMessage mailMessage = new MailMessage();

                mailMessage.From = defaultFrom;
                if (emailTo != null)
                {
                    foreach (string item in emailTo)
                    {
                        mailMessage.To.Add(item);
                    }
                }

                mailMessage.Subject = Subject;
                mailMessage.Body = Body;
                mailMessage.IsBodyHtml = true;
                /// Mark Email as a DRAFT
                mailMessage.Headers.Add("X-Unsent", "1");
                /// ATTACHMENTS FOR EMAIL
                if (serviceFile != null)
                {
                    foreach (ServiceFile item in serviceFile)
                    {
                        if (item.FileBytes != null)
                        {
                            MemoryStream attachmentStream = new MemoryStream(item.FileBytes);

TxWeb/FXAdminTransferConnex/Controllers/TaskReminderController.cs
using FXAdminTransferConnex.Business.TaskReminder;
using FXAdminTransferConnex.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FXAdminTransferConnexApp.Controllers
{
    public class TaskReminderController : BaseAdminController
    {
        #region Initializations

        /// <summary>
        /// The usersService service
        /// </summary>
        private readonly ITaskReminderService _taskReminderService;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskReminderController"/> class.
        /// </summary>
        public TaskReminderController()
        {
            _taskReminderService = EngineContext.Resolve<ITaskReminderService>();
        }
        #endregion

        #region Task Reminder
        // GET: TaskReminder
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// By Datt
        /// 23/10/2019
        /// Update task Reminder
        /// </summary>
        /// <param name="request"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        /// 
        public ActionResult Update(TaskSchedulerModel obj)
        {
            int result;
            result = _taskReminderService.UpdateTaskReminder(obj);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// By Datt
        /// 23/10/2019
        /// Delete task Reminder
        /// </summary>
        /// <param name="request"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        /// 
        public ActionResult Dismiss(long taskID)
        {
            bool result = _taskReminderService.DismissReminder(taskID);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// By Naresh
        /// 23/10/2019
        /// Complete task Reminder
        /// </summary>
        /// <param name="request"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        /// 
        public ActionResult Complete(long taskID)
        {
            bool result = _taskReminderService.CompleteReminder(taskID);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// By Datt
        /// 23/10/2019
        /// Get task Reminder List
        /// </summary>
        /// <param name="request"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        /// 
        public JsonResult GetTaskReminderList(long UserId = 0)
        {
            List<TaskSchedulerModel> list = new List<TaskSchedulerModel>();
            if (UserId > 0)
            {
                list = _taskReminderService.GetTaskReminderList(UserId);
            }
            else
            {
                list = _taskReminderService.GetTaskReminderList(ProjectSession.LoginUserDetails.UserId);
            }

            list.ForEach(x =>
            {
                //if (DateTime.Now.Date > x.Start.Date.Date)
                //{
                //    x.ThemeColor = "#e42307";
                //}
                //else
                //{
                //    x.ThemeColor = "green";
                //}
                if (x.ClientId > 0)
                {
                    // x.ThemeColor = "#E42307";
                    switch (x.ClientLeadCategoryId)
                    {
                        case 1:
                            // Lead
                            x.ThemeColor = "#0000FF";
                            break;
                        case 2:
                            // Hot Lead
                            x.ThemeColor = "#FFA500";
                            break;
                        case 3:
                            // Registered Client
                            x.ThemeColor = "#008000";
                            break;
                        case 4:
                            // Need Documents
                            x.ThemeColor = "#800080";
                            break;
                        case 5:
                            // DING
                            x.ThemeColor = "#E42307";
                            break;
                        case 6:
                            //Sales Lead
                            x.ThemeColor = "#fe2469";
                            break;
                        default:
                            // code block
                            x.ThemeColor = "#E42307";
                            break;
                    }
                }
                if (x.ProspectId > 0)
                {
                    switch (x.ProspectLeadCategoryId)
                    {
                        case 1:
                            // Lead
                            x.ThemeColor = "#0000FF";
                            break;
                        case 2:
                            // Hot Lead
                            x.ThemeColor = "#FFA500";
                            break;
                        case 3:
                            // Registered Client
                            x.ThemeColor = "#008000";
                            break;
                        case 4:
                            // Need Documents
                            x.ThemeColor = "#800080";
                            break;
                        case 5:
                            // DING
                            x.ThemeColor = "#E42307";
                            break;
                        case 6:
                            //Sales Lead
                            x.ThemeColor = "#fe2469";
                            break;
                        default:
                            // code block
                            if(x.ClientId > 0)
                            {
                                x.ThemeColor = "#E42307";
                            }
                            if(x.ProspectId > 0)
                            {
                                x.ThemeColor = "#008000";
                            }
                            break;
                    }
                }

            });
            return new JsonResult { Data = list, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

       
        #endregion
    }
}

TxWeb/FXAdminTransferConnex/Views/Prospect/_OutlookMeeting.cshtml
<script src="~/Content/ckeditor/ckeditor.js"></script>
<style>
    .k-datetimepicker{
        width: 100%;
    }
</style>
<div class="content">
    <div class="panel panel-default">
        <div class="panel-body pb-0">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Subject:</label>
                                <input id="txtMeetingSubjectProspect" type="text" placeholder="Subject" class="k-textbox" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Location:</label>
                                <input id="txtLocation" type="text" placeholder="Location" class="k-textbox" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">Start Date Time:</label>
                                @Html.Kendo().DateTimePicker().Name("txtStartTime")
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">End Date Time:</label>
                                @Html.Kendo().DateTimePicker().Name("txtEndTime")
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Body</label>
                                <textarea rows="6" id="txtMeetingBodyProspect" class="k-textbox"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function sendOutlookMeeting() {
        var Subject = $("#txtMeetingSubjectProspect").val();
        var MailBody = CKEDITOR.instances.txtMeetingBodyProspect.getData();
        var Location = $("#txtLocation").val();
        var StartTime = $("#txtStartTime").val();
        var EndTime = $("#txtEndTime").val();
        var prospectId = $("#ProspectId").val();
        var status = true;

        if (Subject == null || Subject == "") {
            ShowErrorMessage('Meeting subject is required');
            status = false;
            return;
        }
        if (Location == null || Location == "") {
            ShowErrorMessage('Meeting location is required');
            status = false;
            return;
        }
        if (StartTime == null || StartTime == "") {
            ShowErrorMessage('Meeting start time is required');
            status = false;
            return;
        }
        if (EndTime == null || EndTime == "") {
            ShowErrorMessage('Meeting end time is required');
            status = false;
            return;
        }

        if (status) {
            bootbox.confirm("Are you sure want to send meeting invitation? ", function (result) {
                if (result) {
                    var items = [];
                    items.push($("#EmailId").val());
                    
                    $.ajax({
                        url: '@Url.Action("SendOutlookMeeting", "BulkEmail")',
                        async: false,
                        type: 'POST',
                        data: { emailTo: items, Subject: Subject, Body: MailBody, Location: Location, meetingStartTime: StartTime, meetingEndTime: EndTime, ClientId: 0, ProspectId: prospectId },
                        success: function (data) {
                            console.log(data);
                            DisplayResponseMessageForAjax(data);
                            if (data.IsError == 1) {
                                ClearAllMeetinData();
                            }
                        }
                    });
                }
            });
        }
    }

    function ClearAllMeetinData() {
        $("#txtMeetingSubjectProspect").val('');
        $("#txtLocation").val('');
        $("#txtStartTime").val('');
        $("#txtEndTime").val('');
        CKEDITOR.instances.txtMeetingBodyProspect.setData("");
        $('#OutlookMeetingModal').modal('toggle');
    }
</script>
<script>
    CKEDITOR.replace('txtMeetingBodyProspect');
</script>

TxWeb/FXAdminTransferConnex/Views/Prospect/_TaskReminder.cshtml
@using FXAdminTransferConnex.Entities;
@using FXAdminTransferConnex.Common
@using FXAdminTransferConnexApp
@using Kendo.Mvc.UI

@(Html.Kendo().Grid<TaskReminderModel>()
            .Name("gridProspectTaskReminder")
            .Columns(columns =>
            {
                columns.Bound(m => m.Subject).Title("Subject").Width(150);
                columns.Bound(m => m.TaskType).Visible(true).Title("Task Type").Width(150);
                columns.Bound(m => m.AssignToName).Visible(true).Title("Assign To").Width(150);
                columns.Bound(m => m.TaskReminderDatetimeString).Title("Reminder Date time").Width(150);
                columns.Bound(m => m.Notes).Width(150);
                columns.Command(command =>
                {
                    command.Edit().CancelText("Cancel").Text(" ").UpdateText("Save");
                    command.Destroy().Text(" ");
                })
                    .HeaderHtmlAttributes(Common.CenterColumnStyle)
                    .HtmlAttributes(Common.CenterColumnStyle)
                    .Title("Action")
                    .Width(150);
            })
            .ToolBar(toolbar =>
            {
                toolbar.Create().Text("Add Task Reminder").HtmlAttributes(new { @id = "prospectTaskRemind" });

            })
            .Editable(e => e.Mode(GridEditMode.PopUp))
            .Pageable(x =>
            {
                x.Refresh(true);
                x.PageSizes(new int[] { 10, 20, 50, 100 });
            })
            .Selectable(selectable => selectable
            .Mode(GridSelectionMode.Single))
            .Navigatable()
            .Sortable(sortable => sortable.AllowUnsort(false))
            .NoRecords()
            .Events(grid => grid.Edit("Edit"))
            .DataSource(dataSource => dataSource
                .Ajax()
                .ServerOperation(false)
                .PageSize(ConfigItems.GridPageSize)
                .Model(model =>
                {
                    model.Id(d => d.TaskId);
                })
              .Create(update => update.Action("SaveTaskReminder", "Prospect").Data("SetDate"))
              .Update(update => update.Action("SaveTaskReminder", "Prospect").Data("SetDate"))
              .Destroy(delete => delete.Action("DeleteTaskReminder", "Prospect"))
              .Read(read => read.Action("GetTaskReminderList", "Prospect").Data("paraProspectId"))
              .Events(events => events.RequestEnd("onProspectRequestEnd"))
            ))

<script>

    $(document).ready(function () {
        kendoGridScroll();
    });

    //Shows the notifications
    function onProspectRequestEnd(para) {
        if (para.type == 'update' || para.type == 'create' || para.type == 'destroy') {
            $('#gridProspectTaskReminder').data('kendoGrid').dataSource.read();
        }
        DisplayResponseMessage(para);
    }
    
    function paraProspectId() {
        return {
            ProspectId: $('#ProspectId').val()
        }
    }

    function SetDate() {
        var date =  $("#TaskReminderDatetimeString").data("kendoDateTimePicker").value();

        return {
            TaskDateTime: js_dd_mm_yyyy_hh_mm(date)
        }
    }

    function Edit(e) {
        $("input").attr("autocomplete", "off");
        var window = e.container.data("kendoWindow");
        e.model.set("ProspectId", $('#ProspectId').val());

        if (e.model.isNew()) {
            e.model.set("AssignToId",@ProjectSession.LoginUserDetails.UserId);
            e.model.set("TaskTypeId", localStorage.getItem("defaultTaskType"));
            window.title("Add Task Reminder");
        }
        else {
            window.title("Edit Task Reminder");
        }
    };

    $("#gridProspectTaskReminder").delegate("tbody>tr", "dblclick", function () {
        if(!$(this).hasClass('k-grid-edit-row')) {
            $("#gridProspectTaskReminder").data("kendoGrid").editRow($(this));
        }
     });
</script>