TxWeb/FXAdminTransferConnex/Controllers/CommonController.cs
using FXAdminTransferConnex.Business.Common;
using FXAdminTransferConnex.Common;
using FXAdminTransferConnex.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace FXAdminTransferConnexApp.Controllers
{
    public class CommonController : Controller
    {
        #region Initializations

        /// <summary>
        /// The usersService service
        /// </summary>
        private readonly ICommonService _commonService;

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonController"/> class.
        /// </summary>
        public CommonController()
        {
            _commonService = EngineContext.Resolve<ICommonService>();
        }
        #endregion
        // GET: Common
        public JsonResult SetLayOutPageUIToggleFlag()
        {
            try
            {
                ProjectSession.IsMenuSidebarStrip = !ProjectSession.IsMenuSidebarStrip;

                return new JsonResult { Data = true };
            }
            catch (Exception ex)
            {
                return new JsonResult { Data = ex.Message };
            }
        }


        public ActionResult GetUserByRole(int UserTypeId)
        {

            var userList = _commonService.GetUserByUserType(UserTypeId).Select(s => new { Text = s.FirstName, Value = s.UserId }).ToList();
            return Json(userList, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetCategoryList()
        {
            List<CategoryModel> categoryList = _commonService.GetCategoryList().ToList();
            return Json(categoryList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCurrencyList()
        {
            List<CurrencyModel> currencyList = _commonService.GetCurrencyList().ToList();
            return Json(currencyList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMonthList()
        {
            List<MonthModel> MonthList = _commonService.GetMonthList().ToList();
            return Json(MonthList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetYearList()
        {
            List<YearModel> YearList = _commonService.GetYearList().ToList();
            return Json(YearList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTaskTypeList()
        {
            List<TaskTypeModel> List = _commonService.GetTaskTypeList().ToList();
            return Json(List, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetUserList()
        {
            List<UserDDModel> List = _commonService.GetUserList().OrderBy(x => x.FullName).ToList();
            return Json(List, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// By Mayank
        /// 15 March 2018
        /// Gets the list of trade type
        /// </summary>
        /// <returns></returns>
        public ActionResult GetTradeType()
        {
            IEnumerable<SelectListItem> roles = Enum.GetValues(typeof(SystemEnum.TradeType))
                .Cast<SystemEnum.TradeType>()
                .Select(e => new SelectListItem
                {
                    Value = ((int)e).ToString(),
                    Text = e.GetDescription().ToString()
                });
            return new JsonResult
            {
                Data = roles,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        /// <summary>
        /// By Mayank
        /// 15 March 2018
        /// Gets the list of Transaction Status
        /// </summary>
        /// <returns></returns>
        public ActionResult GetTransactionStatus()
        {
            IEnumerable<SelectListItem> roles = Enum.GetValues(typeof(SystemEnum.TransactionStatus))
                .Cast<SystemEnum.TransactionStatus>()
                .Select(e => new SelectListItem
                {
                    Value = ((int)e).ToString(),
                    Text = e.GetDescription().ToString()
                });
            return new JsonResult
            {
                Data = roles,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult GetDealTradeStatus()
        {
            var dealList = _commonService.GetDealTradeStatus().Select(s => new { Text = s.TStatus, Value = s.TStatus }).ToList();
            return Json(dealList, JsonRequestBehavior.AllowGet);
        }

        public static async Task GetCurrencyCloudToken()
        {
            AuthTokenModel resultAPI = new AuthTokenModel();

            Dictionary<string, string> mydict = new Dictionary<string, string>();

            mydict.Add("login_id", ConfigItems.CurrencyCloudAPIEmail);
            mydict.Add("api_key", ConfigItems.CurrencyCloudAPIKey);

            const string uri = "authenticate/api";
            AuthTokenModel result = await WebApiHelper.HttpClientPostCurrencyCloudToken(resultAPI, uri, mydict);

            if (result != null)
            {
                ProjectSession.CurrencyCloudToken = result.auth_token;
            }
        }

        public static async Task GetCurrencyCloudTokenLogout()
        {
            AuthTokenModel resultAPI = new AuthTokenModel();

            const string uri = "authenticate/close_session";
            var result = await WebApiHelper.HttpClientPostCurrencyCloudToken(resultAPI, uri);
            ProjectSession.CurrencyCloudToken = null;
        }

        public JsonResult GetSalesPersonByTraderId(int traderId)
        {
            int userTypeId = SystemEnum.UserType.SalesPerson.GetHashCode();
            List<UserModel> userList = _commonService.GetUserByUserType(userTypeId).Where(x => x.TraderId == traderId).ToList();
            var salespesronList = userList.Select(s => new { Text = s.FirstName, Value = s.UserId }).ToList();
            return Json(salespesronList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetLeadCategoryList()
        {
            List<LeadCategoryModel> leadCategoryList = _commonService.GetLeadCategoryList().ToList();
            return Json(leadCategoryList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTenYearList()
        {
            List<YearModel> model = new List<YearModel>();
            for (int i = 0; i < 10; i++)
            {
                YearModel yearModel = new YearModel();
                int year = DateTime.Now.Year;
                year = year - i;
                yearModel.Year = year;
                model.Add(yearModel);
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PermissionDenied()
        {
            return View("~/Views/Shared/permissiondenied.cshtml");

        }

        public ActionResult GetClientListForDropdown()
        {
            List<ClientMasterModel> leadCategoryList = _commonService.GetClientListForDropdown().ToList();
            JsonResult jsonResult = Json(leadCategoryList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult GetProspectListForDropdown()
        {
            List<ProspectModel> leadCategoryList = _commonService.GetProspectListForDropdown().ToList();
            JsonResult jsonResult = Json(leadCategoryList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult GetCompanyList()
        {
            List<SelectListItem> companyList = _commonService.GetCompanyList().ToList();
            return Json(companyList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetTraderList()
        {
            List<SelectListItem> traderList = _commonService.GetTraderList().ToList();
            return Json(traderList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSalesPersonList()
        {
            List<SelectListItem> salesPersonList = _commonService.GetSalesPersonList().ToList();
            return Json(salesPersonList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSalesPersonListByTrader()
        {
            long traderId = 0;
            if (ProjectSession.LoginUserDetails.UserTypeId == SystemEnum.UserType.Trader.GetHashCode())
            {
                traderId = ProjectSession.LoginUserDetails.TraderId;
            }
            int salespersonuserTypeId = SystemEnum.UserType.SalesPerson.GetHashCode();
            List<UserModel> userList = _commonService.GetUserByUserType(salespersonuserTypeId).Where(x => x.TraderId == traderId).ToList();
            var salesPersonList = userList.Select(s => new { Text = s.FirstName+" "+s.LastName, Value = s.UserId }).ToList();
            return Json(salesPersonList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSectorList(long CategoryId)
        {
            List<SectorModel> SectorList = _commonService.GetSectorList(CategoryId).ToList();
            return Json(SectorList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetBusinessSectorList(int CategoryId)
        {
            List<SectorModel> SectorList = _commonService.GetBusinessSectorList(CategoryId).ToList();
            return Json(SectorList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSalespersonListByTradeId(int UserId)
        {
            List<SelectListItem> Salesperson = _commonService.GetSalespersonListByTradeId(UserId).ToList();
            return Json(Salesperson, JsonRequestBehavior.AllowGet);
        }
    }
}

TxWeb/FXAdminTransferConnex/Controllers/DNDNumberController.cs
using FXAdminTransferConnex.Business.Client;
using FXAdminTransferConnex.Common;
using FXAdminTransferConnex.Entities;
using FXAdminTransferConnex.Entities.LocalizationResource;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FXAdminTransferConnexApp.Controllers
{
    public class DNDNumberController : BaseAdminController
    {
        private readonly IClientService _clientService;

        public DNDNumberController()
        {
            _clientService = EngineContext.Resolve<IClientService>();
        }

        // GET: DNDNumber
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetDNDList_Fordndnumber([DataSourceRequest]DataSourceRequest request, string FullName, string MobileNo)
        {
            List<DNDNumbers> result = _clientService.GetDNDNumberlist(FullName, MobileNo);
            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveDNDNumber(DNDNumbers model)
        {
            int result = _clientService.SaveDNDNumber(model);

            switch (result)
            {
                case -2:
                    ErrorNotification("Number already exist.");
                    return RedirectToAction("ManageNumber", new { DNDNumberID = model.DNDNumberID });
                case 0:
                    ErrorNotification("Error Occur record not saved successfully");
                    return RedirectToAction("ManageNumber", new { DNDNumberID = model.DNDNumberID });
                default:
                    if (model.DNDNumberID > 0)
                        SuccessNotification("Number Updated Successfully");
                    else
                        SuccessNotification("Number Saved Successfully");
                    break;
            }

            return RedirectToAction("Index", "DNDNumber");
        }

        public ActionResult DeleteDNDNumber(long dndNumberId)
        {
            int result = _clientService.DeleteDNDNumber(dndNumberId);

            switch (result)
            {
                case 0:
                    return Json(new { Message = FXAdminTransferConnexResource.Failed, IsError = Enums.NotifyType.Error }, JsonRequestBehavior.AllowGet);
                default:
                    return Json(new { Message = FXAdminTransferConnexResource.DeleteSuccess, IsError = Enums.NotifyType.Success }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ManageNumber(long DNDNumberID = 0)
        {
            DNDNumbers model = new DNDNumbers();
            DNDNumbers responce = _clientService.GetDNDNumberById(DNDNumberID);
            if (responce != null)
            {
                model = responce;
            }
            return View(model);
        }

    }
}

TxWeb/FXAdminTransferConnex/Views/DNDNumber/Index.cshtml
@using FXAdminTransferConnex.Entities;
@using FXAdminTransferConnex.Common
@using FXAdminTransferConnexApp
@using Kendo.Mvc.UI

<div class="content">
    <legend>DND Numbers</legend>
    <div class="panel panel-default">
        <div class="panel-body pb-0">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-lg-3 col-sm-4">
                            <div class="form-group">
                                <input id="txtFullName" type="text" placeholder="Search Name" class="k-textbox" />
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4">
                            <div class="form-group">
                                <input id="txtMobileNo" type="text" placeholder="Search Mobile No." class="k-textbox" />
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4">
                            <div class="form-group">
                                <button id="search" type="button" class="k-button btn-orange">Search</button>
                                <button id="btnReset" type="button" class="k-button btn-orange">Reset</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @* GRID HERE *@

    <fieldset>
        <legend></legend>
        <div class="panel panel-default">
            <div class="panel-body">

                @(Html.Kendo().Grid<DNDNumbers>()
                        .Name("gridDNDNumber")
                        .Columns(columns =>
                        {
                            columns.Bound(m => m.FullName).Width(150);
                            columns.Bound(m => m.MobileNo).Width(150);
                            columns.Bound(m => m.Comments);
                            columns.Command(command =>
                            {
                                if (WebHelper.CanEdit())
                                {
                                    command.Custom("Edit").Text("<span class='k-icon k-edit-white'></span>").Click("onInsert").HtmlAttributes(new { @style = "margin:2px;background: #0833b7;color:white;" });
                                }
                                if (WebHelper.CanDelete())
                                {
                                    command.Custom("Delete").Text("<span class='k-icon k-delete-white'></span>").Click("onDelete").HtmlAttributes(new { @style = "margin:2px;background:#ff1962;color:white;" });
                                    //command.Destroy().Text(" ").HtmlAttributes(new { @style = "margin:2px" });
                                }
                            })
                            .HeaderHtmlAttributes(Common.CenterColumnStyle)
                            .HtmlAttributes(Common.CenterColumnStyle)
                            .Title("Action")
                            .Width(150);
                        })
                        .ToolBar(toolbar =>
                        {
                            if (WebHelper.CanAdd())
                            {
                                toolbar.Custom().Text("Add Number").Url(Url.Action("ManageNumber", "DNDNumber")).HtmlAttributes(new { @class = "k-button btn-orange" });
                            }
                        })
                        .Editable(e => e.Mode(GridEditMode.PopUp))
                        .Pageable(x =>
                        {
                            x.Refresh(true);
                            x.PageSizes(new int[] { 10, 20, 50, 100 });
                        })
                        .Selectable(selectable => selectable
                        .Mode(GridSelectionMode.Single))
                        .Navigatable()
                        .Sortable(sortable => sortable.AllowUnsort(false))
                        .NoRecords()
                        .DataSource(dataSource => dataSource
                        .Ajax()
                        .ServerOperation(false)
                        .PageSize(ConfigItems.GridPageSize)
                        .Model(model =>
                        {
                            model.Id(d => d.DNDNumberID);
                        })
                        .Destroy(delete => delete.Action("DeleteDNDNumber", "DNDNumber"))
                        .Read(read => read.Action("GetDNDList", "DNDNumber"))
                        .Events(events => events.RequestEnd("onRequestEnd"))
                        ))
            </div>
        </div>
    </fieldset>
</div>
<script>
    $(document).ready(function () {
        var havePermission ='@WebHelper.CanView()';
        if (havePermission.toLowerCase()=="false") {
            var urllink = '@Url.Action("PermissionDenied", "Common")';
            window.location.href = urllink;
        }
        kendoGridScroll();
    });

    $('#btnReset').click(function () {
        $('#txtFullName').val('');
        $('#txtMobileNo').val('');
        $('#gridDNDNumber').data('kendoGrid').dataSource.read({
            FullName: $('#txtFullName').val().trim(),
            MobileNo: $('#txtMobileNo').val().trim()
        });
        $('#gridDNDNumber').data().kendoGrid.dataSource.page(1);
    });

    $("#search").click(function () {
        $('#gridDNDNumber').data('kendoGrid').dataSource.read({
            FullName: $('#txtFullName').val().trim(),
            MobileNo: $('#txtMobileNo').val().trim()
        });
        $('#gridDNDNumber').data().kendoGrid.dataSource.page(1);
    });

    $(window).on('keypress', function (e) {
        var key = e.which;
        if (key == 13)  // the enter key code
        {
            $("#search").click();
        }
    });

    //Shows the notifications
    function onRequestEnd(para) {
        if (para.type == 'update' || para.type == 'create' || para.type == 'destroy') {
            $('#gridDNDNumber').data('kendoGrid').dataSource.read();
        }
        DisplayResponseMessage(para);
    }

    function onInsert(e) {
        var DNDNumberID = 0;

        if (e != 0) {
            e.preventDefault();
            var tr = $(e.target).closest("tr");
            var data = this.dataItem(tr);

            if (data != null) {
                DNDNumberID = data.DNDNumberID;
            }
        }
        var urllink = '@Url.Action("ManageNumber", "DNDNumber")';
        window.location.href = urllink + "?DNDNumberID=" + DNDNumberID;
    }

    function onDelete(e) {
        var current = this;
        bootbox.confirm("Are you sure you want to delete this record?",
            function(result) {
                if (result) {
                    var dndNumberId = 0;

                    if (e != 0) {
                        e.preventDefault();
                        var tr = $(e.target).closest("tr");
                        var data = current.dataItem(tr);
                        
                        if (data != null) {
                            dndNumberId = data.DNDNumberID;

                            $.ajax({
                                type: "POST",
                                url: encodeURI('@Url.Action("DeleteDNDNumber", "DNDNumber")'),
                                data: { dndNumberId: dndNumberId },
                                cache: false,
                                async: false,
                                error: function (jqXHR, exception) {
                                },
                                success: function (data) {
                                    if (data) {
                                        DisplayResponseMessageForAjax(data);
                                        $('#gridDNDNumber').data('kendoGrid').dataSource.read();
                                    }
                                }

                            });
                        }
                    }

                    
                }
            });
       
    }
</script>

TxWeb/FXAdminTransferConnex/Views/DNDNumber/ManageNumber.cshtml
@using Kendo.Mvc.UI;
@using FXAdminTransferConnexApp;
@model FXAdminTransferConnex.Entities.DNDNumbers

@{
    ViewBag.Title = "Manage DND Number";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("SaveDNDNumber", "DNDNumber", FormMethod.Post, new { @id = "DNDNumberForm" }))
{
    @Html.HiddenFor(m => m.DNDNumberID)
    <div class="content">
        <legend>DND Number</legend>
        <fieldset>
            <legend></legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Full Name:</label>
                                    @Html.TextBoxFor(m => m.FullName, new { @placeholder = "Full Name", @class = "form-control", @tabindex = "1" })
                                    @Html.ValidationMessageFor(m => m.FullName)
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Mobile No.:</label>
                                    @Html.TextBoxFor(m => m.MobileNo, new { @maxlength = "20", @placeholder = "Mobile No.", @class = "form-control", @tabindex = "2" })
                                    @Html.ValidationMessageFor(m => m.MobileNo)
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label">Comments:</label>
                                    @Html.TextAreaFor(m => m.Comments, new { @placeholder = "Comments", @class = "form-control", @tabindex = "3" })
                                    @Html.ValidationMessageFor(m => m.Comments)
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <a href="@Url.Action("Index", "DNDNumber")" class="btn btn-orange mt-5 mr-10 pull-right" tabindex="5">Cancel</a>
                            <button class="btn btn-orange mt-5 mr-10 pull-right" type="submit" tabindex="4">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
}


<script>
    $(document).ready(function () {
        checkAddeditPermission();
        var validator = $("#TraderForm").kendoValidator().data("kendoValidator");
    });
    function checkAddeditPermission() {
        var havePermission = "false";
        if (@Model.DNDNumberID > 0) {
            havePermission = '@WebHelper.CanEdit()';
        } else {
            havePermission = '@WebHelper.CanAdd()';
        }
        if (havePermission.toLowerCase()=="false") {
            var urllink = '@Url.Action("PermissionDenied", "Common")';
            window.location.href = urllink;
        }
    }
</script>